# Backend
backend = "glx";
glx-no-stutter = true;
glx-no-rebind-pixmap = true;

# Vsync
vsync = true;

# Performance
unredir-if-possible = true;
use-damage = true;

# No fancy effects
fading = false;
shadow = false;
blur-method = "none";
