# shadows
shadow = false;

# transparency
active-opacity = 0.9;
inactive-opacity = 0.8;
frame-opacity = 0.8;

# blur (optional, looks good with st)
blur-method = "dual_kawase";
blur-strength = 5;

# performance
vsync = true;
backend = "glx";

# no shadow on these
shadow-exclude = [
  "class_g = 'dwm'",
  "class_g = 'dmenu'"
#  "class_g = 'firefox'"
];

opacity-rule = [
    "100:class_g = 'firefox-esr'"
];
